### ISSUE TITLE
Printing literal integers uses incorrect static cast leading to wrong value for negatives

### ISSUE THREAD

**Issue by soukainahikma** [pyccel/pyccel#1124]
**Describe the bug**

 Printing integers translates to a ```printf``` with format specifier ```%ld``` which works perfectly with positive numbers but it overflows with negative numbers.

**To Reproduce**
Provide code to reproduce the behavior:
```python
if __name__ == '__main__':
    print(-19)
```
Python output:
```
-19
```

Translated output:
```
4294967277
```

**Language**
C

**Additional context**

C translates the line to:
```c
printf("%ld\n", -19);
```

**Comment by EmilyBourne** [comment]
This is not caused by an overflow but rather it is due to the static cast from `int` to `long int` (which the compiler warns us about). There are 3 possible ways to fix this:
```c
printf("%d\n", -19);
```
```c
printf("%ld\n", int64_t(-19));
```
```c
printf("%ld\n", -19l);
```
I don't have a strong preference for any of these (the first seems like the neatest, but also the hardest to implement in pyccel).
