### ISSUE TITLE
fix and improve issue templates

### ISSUE THREAD

**Issue by rakati** [pyccel/pyccel#1206]
**Describe the feature**
we have for the moment two issue templates, one for the bug and the other for the feature request, the last one has some errata, like  `Describe the bug` instead of `Describe the feature`, so we need to fix the errata and add more useful headline also adding more templates for installation error, documentation issue...
the issue template is located at `https://github.com/pyccel/pyccel/tree/master/.github/ISSUE_TEMPLATE` (`.github/ISSUE_TEMPLATE` folder), you can get inspiration from the issue template used by the Numpy or you can take a look to this repository that has some examples for the issue and PR templates

**Comment by NNRepos** [comment]
hey @rakati, just making sure i understand correctly. what you want to be done is:
* fix incorrect line `Describe the bug`
* add new template: installation error
* add new template: documentation issue

i can work on this, but i believe that the new templates are redundant:
* an installation error is a type of bug,
* and a documentation issue is actually a request to change the documentation, which is a type of feature/enhancement.

please let me know what you think, and assign me if you agree 😄

**Comment by rakati** [comment]
> hey @rakati, just making sure i understand correctly. what you want to be done is:
> 
> * fix incorrect line `Describe the bug`
> * add new template: installation error
> * add new template: documentation issue
> 
> i can work on this, but i believe that the new templates are redundant:
> 
> * an installation error is a type of bug,
> * and a documentation issue is actually a request to change the documentation, which is a type of feature/enhancement.
> 
> please let me know what you think, and assign me if you agree 😄

Yes, I agree with you, the two current templates can be enough and we may just improve them, but it will be better if we separate issues into different types, for example, an installation error needs to have a different issue template than the one for the bug.
@NNRepos this issue is not like other regular issues, you have to think out of the box and come up with ideas for improving our issue templates.
you are free to assign issues to yourself.
@EmilyBourne what do you think?

**Comment by EmilyBourne** [comment]
I think it could be useful to add extra categories. Especially if there is a way to set it up so that it then sends you to the discussions.

For example, most installation problems are not pyccel problems exactly but environment problems. If it can't be fixed then it should live in the FAQs in the discussions.

Similarly there are little features which have an obvious fix and therefore fit in the current template. And there are big features (e.g. I want dictionaries) which require discussion and should live in the Ideas section of the discussion tab.

I agree that documentation is different to adding a new feature. The current templates were written too quickly about 2 days before @rakati and his cohort strated to just have something :sweat_smile:

**Comment by EmilyBourne** [comment]
The trouble with using the same template for everything is that it would have to be very non-specific which makes it easier to ignore

**Comment by EmilyBourne** [comment]
Is anyone working on this? It could be handled with #1245

**Comment by EmilyBourne** [comment]
@rakati can we close this issue? I think it is fixed
