### ISSUE TITLE
Use template in a function with more than 15 entries print warnings

### ISSUE THREAD

**Issue by tomcaruso** [pyccel/pyccel#1337]
### Describe the bug

I have a function with a variable defined by a template with at least 2 possible types and more than 16 arguments. When I try to use Pyccel on such a function, I get warning messages about some integer variable being too large. To be exact, I get 2 messages if I have 16 arguments, 4 messages if I have 17 arguments, etc... 

These warnings appear only if the function has an argument defined by a template with at least 2 types. If a unique type is defined in the template, no warning messages appear.

### To Reproduce

```python
from pyccel.decorators import template

@template(name='T', types=['float[:,:,:,:,:]','complex[:,:,:,:,:]'])
def func(M: 'T', n1: "int64", n2: "int64", n3: "int64", n4: "int64", n5: "int64",
                 p1: "int64", p2: "int64", p3: "int64", p4: "int64", p5: "int64",
                 a1: "int64", a2: "int64", a3: "int64", a4: "int64", a5: "int64"):

    M[n1, n2, n3, n4, n5] = M[p1, p2, p3, p4, p5] + a1 + a2 + a3 + a4 + a5
    return

```
I tried to run the function in the terminal with the command line :
"pyccel file_name.py"

### Error details

```
~/Code/psydac/psydac/api/ast$ pyccel kernel_pyccel.py
/home/cato/venv/psydac/lib/python3.8/site-packages/pyccel/codegen/compiling/compilers.py:431: UserWarning: /home/cato/Code/psydac/psydac/api/ast/__pyccel__/kernel_pyccel_wrapper.c: In function ‘type_check’:
/home/cato/Code/psydac/psydac/api/ast/__pyccel__/kernel_pyccel_wrapper.c:132:1: warning: integer constant is so large that it is unsigned
  132 |         check += INT64_C(11529215046068469760);
      | ^       ~~~~~~~~~~~~~
/home/cato/Code/psydac/psydac/api/ast/__pyccel__/kernel_pyccel_wrapper.c: In function ‘add_2d_wrapper’:
/home/cato/Code/psydac/psydac/api/ast/__pyccel__/kernel_pyccel_wrapper.c:391:1: warning: integer constant is so large that it is unsigned
  391 |     else if (check == INT64_C(11682937913349382690))
      | ^   ~~~~~~~~~~~~~~~~~

  warnings.warn(UserWarning(err))

```

### Expected behavior
It should not print warning message.

### Language
The Python code is translated to Fortran.

**Comment by EmilyBourne** [comment]
Hello,
Thank you very much for reporting this bug.

This happens due to an overly conservative method of determining which `Interface` should be selected. The `Interface` is selected by calculating a flag from the argument types passed to the function.
This flag must be unique for each different combination of arguments, so it is assumed that all arguments may have a different type between interfaces. Looking at the code [here](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/printing/cwrappercode.py#L1092-L1123), it is not entirely clear to me how this flag is determined, but the general idea is that each argument has a certain number of bytes reserved to act as a byte flag indicating its type. We do not seem to reserve fewer bytes if the argument only has one acceptable type.

This  function therefore has quite a bit of room for improvement. If this needs fixing urgently then a patch should be submitted which rewrites the function `pyccel.codegen.printing.cwrappercode.CWrapperPrinter._create_wrapper_check`.
If however it is not urgent then I suggest that I correct this as part of the planned rewriting of this module

**Comment by yguclu** [comment]
@EmilyBourne Tom has encountered this issue while adding the support for complex numbers in Psydac. Using templates is natural as we avoid duplicating lots of code. It appears that the generated code is broken if these warnings are raised.

**Comment by EmilyBourne** [comment]
> @EmilyBourne Tom has encountered this issue while adding the support for complex numbers in Psydac. Using templates is natural as we avoid duplicating lots of code. It appears that the generated code is broken if these warnings are raised.

I agree that the generated code is broken. I'm just not clear on how often this use case is encountered? If it is critical then I think it is possible to get a fix quickly

**Comment by yguclu** [comment]
> > @EmilyBourne Tom has encountered this issue while adding the support for complex numbers in Psydac. Using templates is natural as we avoid duplicating lots of code. It appears that the generated code is broken if these warnings are raised.
> 
> I agree that the generated code is broken. I'm just not clear on how often this use case is encountered? If it is critical then I think it is possible to get a fix quickly

In Psydac this bug is critical, as it will affect almost every function which is accelerated by Pyccel. The only workaround I can see is to duplicate every function which currently accepts `float` arrays and make it accept `complex` arrays.
