### ISSUE TITLE
Dead Interface code in the SemanticParser

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1365]
There are code snippets involving `Interface`s in the `SemanticParser` which are untested. One of these is :
https://github.com/pyccel/pyccel/blob/119d5274a1f7c57cfa0ecbb28dc975e1012cc6f2/pyccel/parser/semantic.py#L2560-L2566
We should check whether this code needs a test (and if so add the test), or if it is dead code which will never be used (e.g. because the `FunctionDef` is extracted from the `Interface` before arriving at this code) and can therefore be deleted.

**Comment by EmilyBourne** [comment]
Duplicate of #1391

**Comment by sboof911** [comment]
After carefully reviewing the code in `core.py`, specifically the `__init__` definition of the `FunctionCall class`,
it seems that there is a condition on line 2135 that checks if the instance of the function is an `Interface`.
https://github.com/pyccel/pyccel/blob/119d5274a1f7c57cfa0ecbb28dc975e1012cc6f2/pyccel/ast/core.py#LL2135C1-L2138C36
However, on line 2138, the function always takes the `FunctionDef type`.
Since the code in core.py is always accessed before calling our code, it appears that this condition is never satisfied.
Therefore, I believe this code segment is dead code and can be safely removed.

**Comment by sboof911** [comment]
After carefully reviewing the code in core.py, specifically the `__init__` definition of the `FunctionCall class`,
it seems that there is a condition on line 2135 that checks if the instance of the function is an `Interface`.
https://github.com/pyccel/pyccel/blob/119d5274a1f7c57cfa0ecbb28dc975e1012cc6f2/pyccel/ast/core.py#LL2135C1-L2139C1
However, on line 2138, the function always takes the `FunctionDef type`.
Since the code in `core.py` is always accessed before calling our code, it appears that this condition is never satisfied.
Therefore, I believe this code segment is dead code and can be safely removed.

**Comment by EmilyBourne** [comment]
I agree. The code you point at is only executed after the syntactic stage. But the code in the semantic stage appears after this line:
https://github.com/pyccel/pyccel/blob/119d5274a1f7c57cfa0ecbb28dc975e1012cc6f2/pyccel/parser/semantic.py#L2489

so we always have a semantically annotated object.

This code:
https://github.com/pyccel/pyccel/blob/119d5274a1f7c57cfa0ecbb28dc975e1012cc6f2/pyccel/parser/semantic.py#L2560-L2569
and the if above it:
https://github.com/pyccel/pyccel/blob/119d5274a1f7c57cfa0ecbb28dc975e1012cc6f2/pyccel/parser/semantic.py#L2528
can be removed, leaving only the body of this `if` (which always returns `True`
