### ISSUE TITLE
COVERAGE : tuples in _visit_Assign Function

### ISSUE THREAD

**Issue by EniddeallA** [pyccel/pyccel#1392]
### Untested code

The untested code is:
https://github.com/pyccel/pyccel/blob/28aa4a5570ff0948ab354307b062ddc65b9a5118/pyccel/parser/semantic.py#L2573-L2609

The problem was discovered in PR : #1385

This problem needs to be investigated. Either a test should be added which uses this code, or the code should be removed.

**Comment by sboof911** [comment]
After doing some tests I found that we can access the two conditions : https://github.com/pyccel/pyccel/blob/28aa4a5570ff0948ab354307b062ddc65b9a5118/pyccel/parser/semantic.py#LL2573C13-L2583C44 and https://github.com/pyccel/pyccel/blob/28aa4a5570ff0948ab354307b062ddc65b9a5118/pyccel/parser/semantic.py#LL2595C13-L2604C30.
But after reviewing this code https://github.com/pyccel/pyccel/blob/28aa4a5570ff0948ab354307b062ddc65b9a5118/pyccel/parser/semantic.py#LL2585C13-L2593C44
the condition `isinstance(d_var, list) and len(d_var)== n` is never satisficed because the type of `d_var` is always a `dictionary` and their is no relation between `len(d_var) and n`; `n` is the number of the variables on the `lhs`; Therefore, I believe this code segment is dead code and can be safely removed.
