### ISSUE TITLE
COVERAGE : dotted variable in _visit_Assign Function

### ISSUE THREAD

**Issue by EniddeallA** [pyccel/pyccel#1398]
### Untested code

The untested code is:
https://github.com/pyccel/pyccel/blob/be45c47c9d2130e30eb4bd943a94c5b44521234d/pyccel/parser/semantic.py#L2440-L2441

The problem was discovered in PR : #1385 

This problem needs to be investigated. Either a test should be added which uses this code, or the code should be removed.

**Comment by EmilyBourne** [comment]
I would expect this line to be tested here:
https://github.com/pyccel/pyccel/blob/c858fef58aabaff942d9a57a6ad27fc4cd13f399/tests/pyccel/scripts/classes/classes.py#L23

If this is not the case then it may well be dead code. We should investigate this example to find the code path.

**Comment by mkaddani** [comment]
Looking at the tests, it's evident that this condition ``elif isinstance(rhs, DottedVariable):``, including lines 2440-2441, has never been executed:
![image](https://github.com/pyccel/pyccel/assets/10669075/ef721e01-fef1-4a73-85fe-ad5812ee55f3)
<br>
executing next  code in commit: fc19f366
```python
class Point(object):
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __del__(self):
        pass

    def translate(self, a, b):
        self.x = self.x + a
        self.y = self.y + b



p = Point(5.6, 9.8)
w = p.x
```
the type of w is ``DottedVariable``, the if condition will be true.
<br>
in current branch ``devel`` executing same code, the type of w is ``DottedName``.
the type of ``w`` will change to ``DottedVariable`` at:
https://github.com/pyccel/pyccel/blob/119d5274a1f7c57cfa0ecbb28dc975e1012cc6f2/pyccel/parser/semantic.py#L2489
since it work in fortran i don't think moving the ``if condition`` under this line will bring any benefit. this ``if condition`` code might be dead.

**Comment by EmilyBourne** [comment]
To be clear `p.x` is `DottedVariable` not `w`.

I agree with your analysis. It cannot be a `DottedVariable` if it has not yet been visited (and then recognised as a `Variable`) so this is all dead code and can be removed.
