### ISSUE TITLE
Pyccelisation of Internal Operation on template variable 

### ISSUE THREAD

**Issue by tomcaruso** [pyccel/pyccel#1427]
### Describe the bug
If we try to use an internal operation on a variable based on a template, pyccel crashed without returning an error message. The Code was working until this commit "Fix AST user tree bug causing problem with AugAssign (https://github.com/pyccel/pyccel/pull/1416)".

### To Reproduce
```python
from pyccel.decorators import template

@template(name='T', types=['float', 'complex'])
def intern_operation_on_template(test_array: 'T'):
    test_array += 1
```

### Error details
```bash
 pyccel kernels.py --language fortran

Traceback (most recent call last):
  File "/home/cato/venv/v_psydac/bin/pyccel", line 33, in <module>
    sys.exit(load_entry_point('pyccel', 'console_scripts', 'pyccel')())
  File "/home/cato/Code/pyccel/pyccel/commands/console.py", line 239, in pyccel
    execute_pyccel(filename,
  File "/home/cato/Code/pyccel/pyccel/codegen/pipeline.py", line 239, in execute_pyccel
    fname, prog_name = codegen.export(fname, language=language)
  File "/home/cato/Code/pyccel/pyccel/codegen/codegen.py", line 205, in export
    code = self._printer.doprint(self.ast)
  File "/home/cato/Code/pyccel/pyccel/codegen/printing/codeprinter.py", line 52, in doprint
    lines = self._print(expr).splitlines(True)
  File "/home/cato/Code/pyccel/pyccel/codegen/printing/codeprinter.py", line 88, in _print
    obj = getattr(self, print_method)(expr)
  File "/home/cato/Code/pyccel/pyccel/codegen/printing/fcode.py", line 466, in _print_Module
    func_strings = [''.join([sep, self._print(i), sep]) for i in expr.funcs]
  File "/home/cato/Code/pyccel/pyccel/codegen/printing/fcode.py", line 466, in <listcomp>
    func_strings = [''.join([sep, self._print(i), sep]) for i in expr.funcs]
  File "/home/cato/Code/pyccel/pyccel/codegen/printing/codeprinter.py", line 88, in _print
    obj = getattr(self, print_method)(expr)
  File "/home/cato/Code/pyccel/pyccel/codegen/printing/fcode.py", line 1929, in _print_FunctionDef
    body_code = self._print(expr.body)
  File "/home/cato/Code/pyccel/pyccel/codegen/printing/codeprinter.py", line 88, in _print
    obj = getattr(self, print_method)(expr)
  File "/home/cato/Code/pyccel/pyccel/codegen/printing/fcode.py", line 1524, in _print_CodeBlock
    line = self._print(b)
  File "/home/cato/Code/pyccel/pyccel/codegen/printing/codeprinter.py", line 88, in _print
    obj = getattr(self, print_method)(expr)
  File "/home/cato/Code/pyccel/pyccel/codegen/printing/fcode.py", line 2069, in _print_AugAssign
    expr.invalidate_node()
  File "/home/cato/Code/pyccel/pyccel/ast/basic.py", line 90, in invalidate_node
    c.remove_user_node(self)
  File "/home/cato/Code/pyccel/pyccel/ast/basic.py", line 384, in remove_user_node
    assert(user_node in self._user_nodes)

```

**Comment by EmilyBourne** [comment]
This is happening due to the reuse of basic nodes (e.g. literals) between the syntactic and semantic stages. The syntactic tree is erased using `expr.clear_user_nodes()` :
https://github.com/pyccel/pyccel/blob/d0fb819671b5b6da4d9da6512a94c9001b9d395e/pyccel/parser/semantic.py#L1902

However in the context of templates this erases the tree associated with the previous type. This is therefore dangerous. 

There are a few solutions to this problem:
1. We could go through `pyccel/parser/semantic.py` and create new instances of these basic classes for the semantic stage. This requires some effort as it also includes the classes which handle OpenMP comments
2. We could remove the call to `expr.clear_user_nodes()` and keep the entire syntactic tree hidden in the semantic tree.
3. We could add an attribute to `pyccel.ast.basic.Basic` indicating the pyccel stage associated with the object. Instead of calling `expr.clear_user_nodes()`  we could then call `expr.clear_syntactic_user_nodes()` and update the stage of these objects.

@yguclu I think the last option makes the most sense as it requires the least effort, it adds a tag which we can use for debgging in the future, and it limits the number of objects which must be created. What do you think?

**Comment by yguclu** [comment]
@EmilyBourne In principle I agree with option (3), as we need a way to track which syntactic nodes are reused in the semantic stage.

Could you please explain what the call  `expr.clear_syntactic_user_nodes()` should do exactly?

Would you keep the current method `clear_user_nodes` for other purposes, or remove it completely?

**Comment by EmilyBourne** [comment]
The current `clear_user_nodes` contains:
https://github.com/pyccel/pyccel/blob/d0fb819671b5b6da4d9da6512a94c9001b9d395e/pyccel/ast/basic.py#L364-L369
It only seems to be used in `parser/semantic.py` so I think we can safely remove it completely.

`expr.clear_syntactic_user_nodes()` should then be:
```
def clear_syntactic_user_nodes(self):
        """ Delete all information about syntactic user nodes. This is useful
        if the same node is used for the syntactic and semantic
        stages.
        """
        self._user_nodes = [u for u in self._user_nodes if u.pyccel_staging != 'syntactic']
```

**Comment by yguclu** [comment]
@EmilyBourne Sounds good to me. Are we sure that the flag `pyccel_staging` will have been changed to `'semantic'` prior to this call?

**Comment by EmilyBourne** [comment]
> @EmilyBourne Sounds good to me. Are we sure that the flag `pyccel_staging` will have been changed to `'semantic'` prior to this call?

I'm not sure what you mean. Are you asking if the users created in the semantic stage will have the semantic flag? The flag should not be changed to `'semantic'` unless the code is reused between the syntactic and semantic stage. In almost every case a new object is created for the semantic stage, which means the object either doesn't yet appear in the tree or has the right flag. In practice the only objects that are reused between the syntactic and semantic stage are simple objects which have no attributes so the problem doesn't appear. If it did then the dev would have to take care of changing the stage at the right moment
