### ISSUE TITLE
Large constants are split in a way that does not appear to be allowed in fortran

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#151]
If a constant is too large for the line (e.g. because the user wants to ensure machine precision) then it can be split in a way that is incompatible with fortran. E.g:

pi = &
      3.141592653589793238462643383279502884197169399375105820974944592

which gives the error:  Error: Unclassifiable statement at (1)

**Comment by yguclu** [comment]
Please be aware that Fortran and C behave differently with regard to literal constants. Fortran real literal constants are single precision by default, so one has to add information about the KIND PARAMETER of the real constant. For example:
```
! Single precision
real(kind=4) :: pi
pi = 3.14159265_4

! Double precision
real(kind=8) :: pi
pi = 3.141592653589793_8
```
If one omits the string "_8" in the literal constant, this is **automatically truncated** to single precision, and then assigned to the double precision variable with lots of trailing zeros...

Because of this, it makes no sense to keep too many digits in literal constants when Fortran code is generated. I definitely suggest to truncate them at the correct position and then add the string "_8" (or the obsolete "_d0", but I would rather not) at the end of them. This way long Python constants will not be a problem.

PS: integer variables also need a KIND PARAMETER.. I think they default to 32 bits.

**Comment by saidctb** [comment]
it is now fixed
