### ISSUE TITLE
MacOS version warning

### ISSUE THREAD

**Issue by dominikbell** [pyccel/pyccel#1526]
### Describe the bug
Since upgrading to MacOS 14.0 compiling any python file prompts the UserWarning: `-macosx_version_min has been renamed to -macos_version_min`

### To Reproduce
Pyccelize any file on MacOS 14.0 or higher.

### Error details
```bash
/Users/dominik/Documents/code/myenv/lib/python3.10/site-packages/pyccel/codegen/compiling/compilers.py:437: UserWarning: -macosx_version_min has been renamed to -macos_version_min
ld: warning: ignoring duplicate libraries: '-lemutls_w', '-lgcc'

  warnings.warn(UserWarning(err))
```

### Expected behavior
No UserWarning

### Language
Fortran (by default)

### Additional context
As reuested [here](https://github.com/pyccel/psydac/issues/341#issuecomment-1746807542).

**Comment by EmilyBourne** [comment]
I assumed this problem was due to these lines:
https://github.com/pyccel/pyccel/blob/devel/pyccel/codegen/compiling/compilers.py#L21-L28
But looking at this in detail I can see that we are setting an environment variable, not changing a compiler flag so I'm not sure of the relevance. Maybe there is none.
According to [this](https://apple.stackexchange.com/questions/464922/weird-message-macos-14-macosx-version-min-has-been-renamed-to-macos-versio) it may be a compiler bug
