### ISSUE TITLE
Add an example on how to use Pyccel to accelerate Python functions (called from Python)

### ISSUE THREAD

**Issue by paugier** [pyccel/pyccel#189]
Hi,

I'd like to try to use Pyccel to accelerate Python functions, but I need to call them from Python (and not to produce a Fortran program).

I didn't find any examples on how to do that in your documentation. There is something written on f2py, but it does not seem that the `pyccel` command line can use f2py and produce a Python extension... 

How would you do that?

For example, how can I produce a C-extension from this module `laplace.py`?

```
import numpy as np

def laplace(image):
    """Laplace operator in NumPy for 2D images."""
    laplacian = (
        image[:-2, 1:-1] + image[2:, 1:-1] + image[1:-1, :-2] + image[1:-1, 2:]
        - 4*image[1:-1, 1:-1]
    )
    thresh = np.abs(laplacian) > 0.05
    return thresh

def laplace_loops(image):
    """Laplace operator for 2D images."""
    h = image.shape[0]
    w = image.shape[1]
    laplacian = np.empty((h - 2, w - 2))
    for i in range(1, h - 1):
        for j in range(1, w - 1):
            laplacian[i-1, j-1] = (
                np.abs(image[i-1, j] + image[i+1, j] + image[i, j-1]
                + image[i, j+1] - 4*image[i, j]) > 0.05
            )
    return laplacian
```

(taken from a Transonic example: https://transonic.readthedocs.io/en/latest/examples/using_jit.html#comparison-numba-vs-transonic)

**Comment by ratnania** [comment]
Hello Pierre,
First of all, thank you for trying Pyccel and sorry for not providing the examples for the moment, but you can find them in our unit tests.
In https://github.com/pyccel/pyccel/blob/master/tests/epyccel/modules/loops.py
we declare different functions for which we add a decorator in order to specify the type of each argument.
These functions are used in the file https://github.com/pyccel/pyccel/blob/master/tests/epyccel/test_loops.py where we compare the accelerated version with the pure python one.
In general, what you should do is the following:
- import the **types** decorator and the **epyccel** function
`from pyccel.decorators import types`
`from pyccel.epyccel import epyccel`
(**epyccel** stands for embedded pyccel)
- assign the types of the arguments using the **types** decorator
- call **epyccel** on your function. Note that you can pass additional arguments like the compiler, flags etc
- **epyccel** will run pyccel then call f2py and return a wrapper to the compiled code

Regarding your example:
- for the moment, we do not handle the naming **np.something**, so you should import what you need in the body of the function you are accelerating. This means that you have to import **empty** from **numpy**. For **abs** you don't need to import it (it's part of Python).
- when calling an array constructor from **numpy** (like **empty**) it is preferable to pass the type as a string. If not found, Pyccel will take the default one, which is double precision.
- in your example, you are assigning a Boolean to a float array. This should not work in Fortran. It is better to add an if statement there.
I hope it helps. 
PS: I started rewriting the documentation recently. It will be available next month.

**Comment by ashwinvis** [comment]
> in your example, you are assigning a Boolean to a float array. This should not work in Fortran. It is better to add an if statement there.

Forgive my ignorance, but it seems that logical arrays are supported in Fortran. Wouldn't that work? Is it a f2py issue or a Fortran issue?

**Comment by paugier** [comment]
> in your example, you are assigning a Boolean to a float array.

Yes the example I posted is not clean at all.

> for the moment, we do not handle the naming np.something

I think it is an important feature.

**Comment by saidctb** [comment]
Hi @paugier your example works with some minor modifications
```python
import numpy as np

def laplace(image:'float[:,:]', thresh: 'bool[:,:]'):
    """Laplace operator in NumPy for 2D images."""
    laplacian = (
        image[:-2, 1:-1] + image[2:, 1:-1] + image[1:-1, :-2] + image[1:-1, 2:]
        - 4*image[1:-1, 1:-1]
    )
    thresh[:,:] = np.abs(laplacian) > 0.05

def laplace_loops(image : 'float[:,:]', laplacian : 'float[:,:]'):
    """Laplace operator for 2D images."""
    h = image.shape[0]
    w = image.shape[1]
    for i in range(1, h - 1):
        for j in range(1, w - 1):
            laplacian[i-1, j-1] = (
                np.abs(image[i-1, j] + image[i+1, j] + image[i, j-1]
                + image[i, j+1] - int(4*image[i, j] > 0.05))
                )
```

**Comment by ashwinvis** [comment]
@saidctb Interesting. Seems like the changes are type annotations in strings (which is OK), and return values as arguments. Can pyccel handle type annotations within the function body instead and keep them as return values? Like:

```py
import numpy as np

def laplace(image:'float[:,:]'):
    ...
    thresh[:,:]: 'bool[:,:]' = np.abs(laplacian) > 0.05
    return thresh

def laplace_loops(image : 'float[:,:]', laplacian):
    ...
            laplacian[i-1, j-1]: 'float[:,:]' = ...
    return laplacian
```

**Comment by saidctb** [comment]
> @saidctb Interesting. Seems like the changes are type annotations in strings (which is OK), and return values as arguments. Can pyccel handle type annotations within the function body instead and keep them as return values? Like:
> 
> ```python
> import numpy as np
> 
> def laplace(image:'float[:,:]'):
>     ...
>     thresh[:,:]: 'bool[:,:]' = np.abs(laplacian) > 0.05
>     return thresh
> 
> def laplace_loops(image : 'float[:,:]', laplacian):
>     ...
>             laplacian[i-1, j-1]: 'float[:,:]' = ...
>     return laplacian
> ```
the problem is in returning numpy arrays and not in the type annotation, which we don't handle for the moment
