### ISSUE TITLE
Remove external decorator

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#228]
The @external decorator is unnecessary and forgetting it leads to behaviour that is not intuitive. It exists in order to allow methods to be private however this concept doesn’t exist in python. Instead if we only wish to see certain functions then we only import those functions or we separate the ‘private’ and ‘public’ functions into different files and only import the ‘public’ file. This methodology can be used in the same way be externalising all functions. Thus it does not seem necessary to create an @internal or @private decorator which would replace @external and do the opposite (more intuitive).

**Comment by yguclu** [comment]
The `@external_call` decorator should also be removed. It is similar to `@external`, but for subroutines instead of functions.

**Comment by yguclu** [comment]
I suggest we treat as "internal" (i.e. not to be exposed outside of the module where it is defined) any function with a name that starts with an underscore `_`. Everything else will be "external" by default.

@ratnania @saidctb @EmilyBourne @krystophny: what do you think?

**Comment by krystophny** [comment]
Think too. Would even go as far as exporting underscored routines, since this is useful for debugging purposes and like in Python. But that's a matter of preference.

**Comment by yguclu** [comment]
Actually my suggestion is based on some practical issues, rather than preference.

On the one hand, module symbols starting with an underscore can only be imported explicitly, and they are automatically excluded when one writes `from module import *`. So it seems natural to treat them as `internal` symbols.

On the other hand, Fortran does not allow names starting with an underscore, so we need to rename any function with such a name. This makes it tricky to import the renamed function from another module.

**Comment by krystophny** [comment]
Hm... I see. one could call underscored methods `private_...` in Fortran then, and make an alias for calling via Python.
