### ISSUE TITLE
Automatic array allocation via type inference

### ISSUE THREAD

**Issue by krystophny** [pyccel/pyccel#245]
The following Python code
```python
@types('real[:], real[:], real[:]')
def array_real_loopdiff(x, y, out):
    dxy = x - y
    for k in range(len(x)):
        out[k] = dxy[k]
```

generates Fortran code where `real(kind=8), allocatable :: dxy (:) ` is not started with zero indexing, namely

```Fortran
subroutine array_real_loopdiff(x, y, out) 

  implicit none
  real(kind=8), intent(in)  :: x (0:)
  real(kind=8), intent(in)  :: y (0:)
  real(kind=8), intent(inout)  :: out (0:)
  real(kind=8), allocatable :: dxy (:) 
  integer(kind=8) :: k  

  dxy = x - y
  do k = 0, size(x,1) - 1_8, 1
    out(k) = dxy(k)
  end do

end subroutine
```

This leads to failure. Have added according case in `tests/epyccel/test_arrays.py` in branch `test_fffi` in d5cd435fc71fe18d4cbf185994bb2771a3335250.

**Comment by yguclu** [comment]
I will add a fix for this bug to pull request #237

**Comment by yguclu** [comment]
Given that we assume 0-based indexing for all Fortran arrays, I think we are missing the line
```
allocate( dxy(0:size(x, 1)) )
```
just before the assignment
```
dxy = x - y
```
Hence the allocatable array `dxy` is automatically allocated to the correct shape, but it will use the default 1-based indexing.

It should be noted that the assignment `dxy = x - y` is not safe even if `dxy` was already allocated, because  `x - y` could have a different shape of `dxy`; in this case `dxy` will be automatically deallocated and reallocated to the new shape. This kind of behavior is part of the Fortran standard, but not all compilers are happy to support it (by default ifort does not support it) because it hinders optimizations.

For the reasons above I think we should always avoid automatic allocations, and write instead:
```
allocate( dxy(0:size(x, 1)) )
dxy(:) = x - y
```

**Comment by krystophny** [comment]
Does this mean that even if I don't explicitly write allocate, Fortran will allocate dxy in every function call? Is this not inlined away somehow if I just write
```
real :: dxy(0:)
```
?

**Comment by yguclu** [comment]
> Does this mean that even if I don't explicitly write allocate, Fortran will allocate dxy in every function call? Is this not inlined away somehow if I just write
> 
> ```
> real :: dxy(0:)
> ```
> 
> ?

I think you cannot specify 0-indexing on an allocatable array until you explicitly allocate it.

**Comment by yguclu** [comment]
A complete fix for this bug requires inferring the shape of any expression passed on the right-hand side. We will do that in the future. For now we avoid any automatic allocation by requiring the left-hand side variable to be already allocated. Hence your example will raise a `NotImplementedError`.

**Comment by krystophny** [comment]
Changed this to an enhancement for automatic allocation based on type inference. Now an exception is thrown correctly, so one should change the test case to check that accordingly.
