### ISSUE TITLE
A multi object part of a numpy array is stored in a sympy Tuple

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#340]
This means that the following code without the return statement can be translated:
```
def tuple_multi_indexing_2():
    from numpy import ones
    x = ones((2,3,2))
    for z in range(2):
        for y in range(3):
            for w in range(2):
                x[z,y,w] = w+y*2+z*6
    idx = (1,1,0)
    idx_2 = (0,1,2)
    ai = x[idx,idx_2,1]
    return ai[0], ai[1], ai[2]
```
But as soon as we interact with `ai` it no longer works

**Comment by yguclu** [comment]
This kind of indexing into a Numpy array is fairly sophisticated and not much widespread (luckily): https://numpy.org/devdocs/user/basics.indexing.html#indexing-multi-dimensional-arrays

Clearly the result should be a Numpy array, but computing its shape is not straightforward. Pyccel needs to be able to compute its rank, so we can use an `allocatable` array and defer the exact shape calculation to runtime.

**Comment by EmilyBourne** [comment]
I don't know whether the result should be an `allocatable` array or simply a tuple. I was expecting a Pyccel Tuple in which case this should already be handled

**Comment by yguclu** [comment]
In Python the result is a new `numpy.ndarray` with its own allocated memory, where the data is copied rather than just referenced through a view. So I think we should use an allocatable array in the generated Fortran code. Of course we will switch to an automatic array if the user declares it with `@stack_array('ai')`.
