### ISSUE TITLE
missing semicolon when performing standalones arithmetic or bitwise operations

### ISSUE THREAD

**Issue by rmahjoubi** [pyccel/pyccel#425]
**Performing a standalone arithmetic or bitwise operation leads to a missing semicolon in c**
performing an arithmetic operation without it being assigned to a variable nor being inside an if or while statement... leads to a missing semicolon in the generated code.

**To Reproduce**

```
@types('int', 'int')
def sum_two_numbers(x, y):
    x + y
```

**The Generated Code**
```
void sum_two_numbers(long x, long y)
     x + y
```

**Error Message**
```
/.../__pyccel__/ntest.c: In function ‘sum_tow_numbers’:
/.../__pyccel__/ntest.c:4:7: warning: statement with no effect [-Wunused-value]
     x + y
     ~~^~~
/.../__pyccel__/ntest.c:5:1: error: expected ‘;’ before ‘}’ token
 }
 ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Language**
C

**Comment by EmilyBourne** [comment]
Currently in pyccel we have no way to tell what exactly is a line. The closest thing we have to this is the `CodeBlock` object which should contain a list of lines. However it does not make sense to simply add a semi-colon to everything in a `CodeBlock` as this would also add a semi-colon to the end of an `If` block which is redundant.

Pyccel usually relies on the user creating correct python code. I think we can also trust the user to write code that does something. If they do not then the compiler error `statement with no effect` seems to be sufficiently clear to me.

Do you agree @saidctb @yguclu ?

**Comment by yguclu** [comment]
I think Python performs every given instruction because it has no way to tell if this is meaningful or not. For example, `a + b` could have any sort of behavior (and side effects) if `a` (or `b)` is an instance of a user-defined type with magic function `__add__` (or `__radd__`).

Thanks to the type annotations Pyccel knows that `a + b` is dealing with integers, and hence nothing happens. So maybe we could remove from the AST the nodes that do not contain assignments or other control blocks. But when we do so, we should most definitely raise a warning.

**Comment by saidctb** [comment]
yes I agree I prefer to ignore them in the printing process when we print `CodeBlock`

**Comment by EmilyBourne** [comment]
@saidctb I don't think we have this information anymore once we get to the printing stage. It think we would have to remove them in the semantic or even syntactic stage

This solution sounds sensible to me

**Comment by saidctb** [comment]
> @saidctb I don't think we have this information anymore once we get to the printing stage. It think we would have to remove them in the semantic or even syntactic stage
> 
> This solution sounds sensible to me

why ? the information exist in the `CodeBlock` where the possible statements are `Assign, FunctionCall , Loop, If, Return`
otherwise it's not printed ,or we can just check if a statement is an operator if yes then it's not printed

**Comment by EmilyBourne** [comment]
Ah ok perfect then :) I didn't realised there was a definite list of acceptable statements for `CodeBlock`. Presumably these standalones cannot be in an object other than a `CodeBlock`?

Presumably you would rather this be in the printing step so that they are only removed in C code? Is there any value to keeping them in other languages? Does the compiler not issue warnings about standalones?

**Comment by yguclu** [comment]
I would favor removing the "useless" instructions at the semantic stage, as they are useless in Python, C and Fortran alike.
