### ISSUE TITLE
Semantic parser is extremely slow at processing long expressions

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#815]
Bug description
--------------------
Pyccel is extremely slow when it processes long expressions.

To Reproduce
--------------------
The following function is extremely slow to parse, and it effectively hangs on my computer:

```python
def determinant_4x4(M: 'float[:,:](order=C)') -> 'float':
    return (
          M[0,0] * M[1,1] * M[2,2] * M[3,3]
        + M[0,0] * M[1,2] * M[2,3] * M[3,1]
        + M[0,0] * M[1,3] * M[2,1] * M[3,2]
        + M[0,1] * M[1,0] * M[2,3] * M[3,2]
        + M[0,1] * M[1,2] * M[2,0] * M[3,3]
        + M[0,1] * M[1,3] * M[2,2] * M[3,0]
        + M[0,2] * M[1,0] * M[2,1] * M[3,3]
        + M[0,2] * M[1,1] * M[2,3] * M[3,0]
        + M[0,2] * M[1,3] * M[2,0] * M[3,1]
        + M[0,3] * M[1,0] * M[2,2] * M[3,1]
        + M[0,3] * M[1,1] * M[2,0] * M[3,2]
        + M[0,3] * M[1,2] * M[2,1] * M[3,0]
        - M[0,0] * M[1,1] * M[2,3] * M[3,2]
        - M[0,0] * M[1,2] * M[2,1] * M[3,3]
        - M[0,0] * M[1,3] * M[2,2] * M[3,1]
        - M[0,1] * M[1,0] * M[2,2] * M[3,3]
        - M[0,1] * M[1,2] * M[2,3] * M[3,0]
        - M[0,1] * M[1,3] * M[2,0] * M[3,2]
        - M[0,2] * M[1,0] * M[2,3] * M[3,1]
        - M[0,2] * M[1,1] * M[2,0] * M[3,3]
        - M[0,2] * M[1,3] * M[2,1] * M[3,0]
        - M[0,3] * M[1,0] * M[2,1] * M[3,2]
        - M[0,3] * M[1,1] * M[2,2] * M[3,0]
        - M[0,3] * M[1,2] * M[2,0] * M[3,1]
    )
```

This can be shown by calling pyccel with the `-e` flag, which stops execution after the semantic stage:

```bash
$ pyccel -e test.py
```

By commenting out most of the expression, and progressively increasing the number of lines it contains, one can see that the problem arises when the number of lines approaches 10.

Expected behavior
-----------------------
Pyccel should be able to process long expressions without any problems.

Language
-------------
This is a problem in the semantic parser. As such, it is independent of the language.

**Comment by EmilyBourne** [comment]
The cause of this problem is the double visitation of the arguments to `PyccelOperator` (specifically `PyccelAdd`, `PyccelMul`) as seen [here](https://github.com/pyccel/pyccel/blob/master/pyccel/parser/semantic.py#L1196-L1229).
This becomes prohibitively expensive as the depth of the nested operators increases as in order to create each operator we must:
- create the arguments
- tear down the arguments
- recreate the arguments

This is done in order to handle tuple operations. E.g.:`(1,2,3)*2`
In order to recognise these cases the arguments must be visited as the presence of tuples is not detectable in our code in its current state without visitation. E.g.:
```
a = ((1,2,3) + (4,5,6)) * 2
```
when visiting the `PyccelMul` operator the first argument is a `PyccelAdd` with dtype `int`

There are 3 possible solutions:
1. Pass the visited args as an optional argument to `_visit_PyccelOperator`
2. Duplicate the code in `_visit_PyccelOperator` in `_visit_PyccelAdd` and `_visit_PyccelMul`
3. Rework tuples so their presence is evident from the dtype
