### ISSUE TITLE
Wrong generated code in Python when using print function

### ISSUE THREAD

**Issue by nhamidn** [pyccel/pyccel#868]
**Describe the bug**
The Python printer generate a code with an invalid syntax, when using the print function

**To Reproduce**
```python
def func():
    print("test")

    a = 0
```

Generated to this:
```python
from pyccel.decorators import types

def func():
    print('test')a = 0
```
And

This code
```python
def func():
    for i in range(7):
        print("test")

    a = 0
```

Generated to this:
```python
from pyccel.decorators import types

def func():
    for i in range(0, 7, 1):
        print('test'
    a = 0
```

Per my testing it does not appear to use the `_print_Print` method in `pycode.py`

**Language**
Python

**Comment by EmilyBourne** [comment]
This is mentioned in issue #865. It is caused by the [indentation of the code](https://github.com/pyccel/pyccel/blob/master/pyccel/codegen/printing/pycode.py#L62-L68). The indentation strips the last character (assumed to be `'\n'`) from the string before replacing all `'\n'` characters with `'\n    '`. However in this case the `'\n'` is missing from `_print_PythonPrint`. The simplest fix is to add the missing character, but it may be worth modifying the indentation function to prevent this kind of bug in the future by using `.strip('\n')`.

This bug is currently not covered by our tests as the tests in the `pyccel/` folder do not test python yet (see issue #643 )
