### ISSUE TITLE
TypeError messages in numpyext.py are not raising 

### ISSUE THREAD

**Issue by nhamidn** [pyccel/pyccel#916]
**Describe the bug**
TypeError messages in numpyext.py are not raising, and UNRECOGNISED_FUNCTION_CALL error message is raised instead. 

**To Reproduce**
For example this python code tested in `linspace_where_argument` branch:
```python
from pyccel.decorators import types
@types('float[:]','int')
def get_linspace(start, stop):
    from numpy import linspace, array
    num = 7.5
    a = linspace(start, stop, num, endpoint=False)
```

Generate this sematic error message
```bash/fortran/c
Function call cannot be processed. Please ensure that your code runs correctly in python. If this is the case then you may be using function arguments which are not currently supported by pyccel. Please create an issue at https://github.com/pyccel/pyccel/issues and provide a small example of your problem. (linspace(start, stop, num, endpoint=False))
```

**Expected behavior**
the generated error message must be:
`Expecting positive integer num argument.`
but because of the `try except` in the semantic stage [here](https://github.com/pyccel/pyccel/blob/1392febfb9707842540cc1159b65403f84fd5e82/pyccel/parser/semantic.py#L1033), the type error is not raised.

**Language**
Python, C and Fortran

**Comment by EmilyBourne** [comment]
`TypeError` messages are for developers. These messages are not caught and cause ugly results for the user. If you want to raise an error that is readable by the user then you should use a `PyccelError` type. If the problem is about seeing the error, then maybe you can try running with `--developer-mode`? This message was added to handle cases like [this](https://github.com/pyccel/pyccel-examples/blob/main/BUGS.md#bugs-2). Do you have a suggestion about how we can do both? (Make the `TypeError` messages visible to developers but don't throw a traceback at users if they write incorrect code or use arguments which we haven't implemented yet)

**Comment by EmilyBourne** [comment]
Actually in this case the code in your example doesn't run in python. So I am not sure why it is strange to see an error that says:
```
Please ensure that your code runs correctly in python
```
?

**Comment by nhamidn** [comment]
> Actually in this case the code in your example doesn't run in python. So I am not sure why it is strange to see an error that says:
> 
> ```
> Please ensure that your code runs correctly in python
> ```
> 
> ?

in this case the code does not work in pure python also

**Comment by EmilyBourne** [comment]
> > Actually in this case the code in your example doesn't run in python. So I am not sure why it is strange to see an error that says:
> > 
> > ```
> > Please ensure that your code runs correctly in python
> > ```
> > 
> > ?
> 
> in this case the code does not work in pure python also

That's my point. That's exactly what the error says, so where is the problem?

**Comment by nhamidn** [comment]
i see now, the user must be responsible for it's own python code, this issue can be closed
